version: '3.8'

services:
  nginx:
    image: nginx:stable  # Nginx 공식 stable 이미지 사용
    container_name: nginx
    network_mode: "host"  # --network host
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - DOMAIN=${DOMAIN}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
    volumes:
      - /etc/nginx/sites-available/default:/etc/nginx/conf.d/default.conf:ro  # Nginx 설정 파일 마운트 (읽기 전용)
      - /etc/letsencrypt:/etc/letsencrypt:ro  # SSL 인증서 마운트 (읽기 전용)
      - ./cicd/html:/usr/share/nginx/html  # 정적 파일 마운트
    restart: always  # 컨테이너가 종료되면 자동 재시작