server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url : ${SPRING_DATASOURCE_URL}
    username : ${SPRING_DATASOURCE_USERNAME}
    password : ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true # 하이버네이트가 테이블 만들고 data.sql실행보장.

  logging:
    level:
      org.hibernate.SQL: debug  # SQL 쿼리 로그 출력
      org.hibernate.type: trace # SQL 쿼리 파라미터 로그 출력
      com.your.package: debug
      org.hibernate.tool.hbm2ddl: debug  # 스키마 생성 관련 로그
  sql:
    init:
      mode: always